- name: check tilt command
  command: which tilt
  register: tilt_check
  failed_when: no
  changed_when: no

- block:
  - name: Download tilt
    get_url:
      url="https://github.com/tilt-dev/tilt/releases/download/v0.31.1/tilt.0.31.1.linux.x86_64.tar.gz"
      dest="/opt/tilt.0.31.1.linux.x86_64.tar.gz"

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /opt/tilt
      state: directory

  - name: Extract the downloaded file
    command: tar -xvzf /opt/tilt.0.31.1.linux.x86_64.tar.gz -C /opt/tilt

  - name: Remove tilt's packaged
    ansible.builtin.file:
      path: /opt/tilt.0.31.1.linux.x86_64.tar.gz
      state: absent

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /opt/tilt/tilt
      dest: /usr/local/bin/tilt
      owner: root
      group: root
      state: link
  when: tilt_check.rc != 0
