apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.124.0
        env:
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse
              key: admin-password
        ports:
        - containerPort: 4317 # gRPC
        - containerPort: 4318 # HTTP
        - containerPort: 54526
          protocol: UDP
        volumeMounts:
        - name: otel-config
          mountPath: /etc/otelcol-contrib/config.yaml
          subPath: config.yaml
      volumes:
      - name: otel-config
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  type: LoadBalancer
  ports:
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: grpc
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: http
  - port: 54526
    targetPort: 54526
    protocol: UDP
    name: udp-syslog
  selector:
    app: otel-collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      syslog:
        udp:
          listen_address: "0.0.0.0:54526"
        protocol: rfc5424
        location: UTC
        operators:
        - type: regex_parser
          parse_from: attributes.message
          regex: '^(?<cache_status>[^|]*)\|(?<status_code>[^|]*)\|(?<timestamp>[^|]*)\|(?<bytes_sent>[^|]*)\|(?<pull_zone_id>[^|]*)\|(?<remote_ip>[^|]*)\|(?<referer_url>[^|]*)\|(?<url>[^|]*)\|(?<edge_location>[^|]*)\|(?<user_agent>[^|]*)\|(?<unique_request_id>[^|]*)\|(?<country_code>[^|]*)$'
          timestamp:
            parse_from: attributes.timestamp
            layout_type: epoch
            layout: ms

    processors:
      batch:
        # send_batch_size: 1000
        # timeout: 10s
        # send_batch_max_size: 1000

    exporters:
      debug:
        verbosity: detailed
      clickhouse:
        endpoint: tcp://clickhouse:9000
        username: default
        password: $CLICKHOUSE_PASSWORD
        database: default
        create_schema: false
        logs_table_name: otel_logs
        timeout: 5s

    service:
      pipelines:
        logs:
          receivers: [ syslog ]
          processors: [ batch ]
          exporters: [ debug, clickhouse ]
