host: "discourse.digisense.io"
discourse:
  plugins:
  - https://github.com/discourse/discourse-openid-connect
auth:
  email: devadmin@apiplus.tech
  username: admin
smtp:
  enabled: true
  host: smtp.postmarkapp.com
  port: 587
  user: 03f5d05f-8f5b-455e-9acc-cc116f7c3fec
  password: 03f5d05f-8f5b-455e-9acc-cc116f7c3fec
  protocol: tls
postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "test"
    username: "admin"
    password: "admin1234"
    database: discourse
