{
 "title": "PGBouncer",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "pgnodes",
    "label": "PGCluster",
    "query": "label_values(ccp_pgbouncer_pools_client_active, pg_cluster)"
   },
   {
    "name": "conn_pool",
    "label": "Connection Pool",
    "query": "label_values(ccp_pgbouncer_pools_client_active{pg_cluster=~\"[[pgnodes]]\"}, conn_pool)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connection % Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ccp_pgbouncer_databases_db_conn_perc_used{pg_cluster=~\"[[pgnodes]]\"}",
     "legendFormat": "{{pool_db}}"
    }
   ]
  },
  {
   "title": "PGBouncer Total State Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ccp_pgbouncer_pools_client_active{pg_cluster=~\"[[pgnodes]]\"})",
     "legendFormat": "client_active"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_client_waiting{pg_cluster=~\"[[pgnodes]]\"})",
     "legendFormat": "client_waiting"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_active{pg_cluster=~\"[[pgnodes]]\"})",
     "legendFormat": "server_active"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_idle{pg_cluster=~\"[[pgnodes]]\"})",
     "legendFormat": "server_idle"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_used{pg_cluster=~\"[[pgnodes]]\"})",
     "legendFormat": "server_used"
    }
   ]
  },
  {
   "title": "PGBouncer Item Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ccp_pgbouncer_lists_item_count{pg_cluster=~\"[[pgnodes]]\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Client Connection Counts Per Pool - [[pgnodes]] - [[conn_pool]]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ccp_pgbouncer_clients_client_state_count{pg_cluster=~\"[[pgnodes]]\", conn_pool=\"[[conn_pool]]\"}",
     "legendFormat": "{{client_state}}"
    }
   ]
  },
  {
   "title": "Server Connection Counts Per Pool - [[pgnodes]] - [[conn_pool]]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ccp_pgbouncer_servers_server_state_count{pg_cluster=~\"[[pgnodes]]\", conn_pool=\"[[conn_pool]]\"}",
     "legendFormat": "{{server_state}}"
    }
   ]
  }
 ]
}