{
 "title": "USE Method",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (node)"
    }
   ]
  },
  {
   "title": "memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes) by (instance) \n/ sum(node_memory_MemTotal_bytes) by (instance)"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate5m * 9.537*10^-7",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate5m * 9.537*10^-7",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk percentage free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{mountpoint=\"/\"}) by (instance) / sum(node_filesystem_size_bytes{mountpoint=\"/\"}) by (instance)"
    }
   ]
  }
 ]
}