kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: traefik-ingress
  namespace: traefik

spec:
  rules:
    - host: shop.naaraan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: naaraan
                port:
                  number: 5000