apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: mysql
  name: db-pvc
spec:
  # storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bookstack
  name: uploads-pvc
spec:
  # storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bookstack
  name: storage-uploads-pvc
spec:
  # storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi