apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  GITHUB_WEBHOOK_SECRET: qxtrokamgnuuivszopoadgycjsumkytrabjrqjipkipepocihaaxynadwpqwesyupdkypszzihzaiqnodjhndhwinxytxtxzbwayemthjlkefcqiwybidvaxpvvtwken
