---
# tasks that run after a new deployment

- name: Install AD Domain packages
  apt: 
    name: "{{ item }}"
    state: present 
    update_cache: yes
  vars:
    item:
    - sssd-ad
    - sssd-tools
    - realmd
    - adcli
    - samba-common-bin
  tags: ad

# - name: Copy realmd.conf
#   template: 
#     src: realmd.conf.j2
#     dest: /etc/realmd.conf
#     owner: root
#     group: root
#     mode: 0644
#   tags: ad

# - name: Copy krb5.conf
#   template: 
#     src: krb5.conf.j2
#     dest: /etc/krb5.conf
#     backup: yes
#     owner: root
#     group: root
#     mode: 0644
#   tags: ad

- name: Discover realm
  command: /bin/bash -c "/usr/sbin/realm discover {{ ad_realm }}"
  register: realm_discover_results
  tags: ad

- name: Discover realm debug
  debug: 
    msg: "{{ realm_discover_results.stdout }}"

# - name: Create kerberos ticket
#   expect:
#     command: /bin/bash -c "/usr/bin/kinit -V {{ bind_user }}"
#     responses:
#       (?i)Password: "{{ bind_user_password }}"
#   tags: ad

# Check for existing AD
- name: Checking to see if system is already joined to AD
  command: /bin/bash -c "/usr/sbin/realm list"
  register: realm_list_results
  tags: ad

- name: Debug realm_list_results
  debug:
    msg: "{{ realm_list_results.stdout }}"

- name: Join system to AD
  shell: echo "{{ bind_user_password }}" | realm join "{{ ad_realm_domain }}" --computer-ou="{{ ad_realm_ou }}" --user="{{ bind_user }}"
  ignore_errors: true
  when: realm_list_results.stdout == ""
  register: realm_join_results
  become: true
  tags: ad

- name: Debug realm_join_results
  when: realm_list_results.stdout == ""
  debug:
    msg: "{{ realm_join_results.stdout }}"

- name: Copy suders file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.bak

- name: Add domain admins group to sudoers
  lineinfile: dest=/etc/sudoers.tmp state=present line='%domain\ users ALL=(ALL:ALL) ALL' regexp='^%domain'

- name: Final sudoers file check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers

- name: Copy sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  tags: ad

- name: Restart service sssd
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: Automatic home directory creation
  ansible.builtin.shell: pam-auth-update --enable mkhomedir

- name: Copy startup login script
  template:
    src: startup.sh.j2
    dest: /etc/skel/startup.sh
    owner: root
    group: root
    mode: 0755