- name: "Fetching Kubernetes Master PKI files from primary master"
  fetch:
    src: /etc/kubernetes/pki/{{item}}
    dest: /tmp/kubeadm-ha/pki/{{item}}
    flat: yes
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key

- name: "Fetching Kubernetes Master ETCD files from primary master"
  fetch:
    src: /etc/kubernetes/pki/etcd/{{item}}
    dest: /tmp/kubeadm-ha/pki/etcd/{{item}}
    flat: yes
  with_items:
    - ca.crt
    - ca.key
