- name: Generate master join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{groups['k8s_master_primary'][0]}}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Join Master replicas to cluster
  shell: "{{ kubeadm_join }} >> join_master.txt"
  args:
   chdir: $HOME
   creates: join_master.txt