- hosts: master
  become: yes
  tasks:
  - name: remove swap
    shell: "swapoff -a"

  - name: initialize the cluster
    shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
    args:
     chdir: $HOME
     creates: cluster_initialized.txt

  - name: create .kube directory
    become: yes
    become_user: azureuser
    file:
     path: $HOME/.kube
     state: directory
     mode: 0755

  - name: copy admin.conf to user's kube config
    copy:
     src: /etc/kubernetes/admin.conf
     dest: /home/azureuser/.kube/config
     remote_src: yes
     owner: azureuser

  - name: install Pod network
    become: yes
    become_user: azureuser
    shell: |
      kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml