apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  script.sh: |
    #!/bin/sh

    curl -L -o /home/curl_user/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    chmod +x jq
    export PATH="/home/curl_user:$PATH"


    curl -s -X GET https://admin:XS\!p4b3\!DsnGfWU@couch.digisense.io/_all_dbs >> quickpage-list.txt


    # Specify the file path
    file_path="quickpage-list.txt"

    if [ -f "$file_path" ]; then
        # Use jq to parse the JSON array and iterate over its elements
        elements=$(jq -r '.[]' "$file_path")

        # Iterate over the elements using a for loop
        for element in $elements; do
            num_doc=$(curl -s -X GET https://admin:XS\!p4b3\!DsnGfWU@couch.digisense.io/$element | jq '.doc_count')
            if [ "$num_doc" = "0" ]; then
                curl -s -X DELETE https://admin:XS\!p4b3\!DsnGfWU@couch.digisense.io/$element >> /dev/null
            fi
        done
    else
        echo "File not found: $file_path"
    fi
