# [[file:../../README.org::*Creating our first certificate][Creating our first certificate:1]]
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dicast-site
  namespace: istio-system
spec:
  # The secret name where cert-manager should store the signed certificate
  secretName: dicast-site-tls
  dnsNames:
  - "*.dicast.site"
  # Duation of the certificate
  duration: 8760h
  # Renew a day before the certificate expiration
  renewBefore: 720h
  # Reference the Origin CA Issuer you created above, which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer

# Creating our first certificate:1 ends here
