services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=pass
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  clickhouse-data:
