kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-portforward
rules:
- apiGroups: [ "" ]
  resources: [ "pods/portforward" ]
  verbs: [ "create" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-portforward
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-portforward
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
