apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hydra.yaml

configMapGenerator:
- name: ory-hydra-config
  files:
    - hydra/hydra.yml

generatorOptions:
 disableNameSuffixHash: true