- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: add Docker apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add Docker' APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ host_version_codename }} stable
    state: present
    filename: 'docker'
    update_cache: true

- name: install docker-ce
  apt:
    name: docker-ce={{docker_version}}
    state: present
    update_cache: true

- name: install docker-ce-cli
  apt:
    name: docker-ce-cli={{docker_version}}
    state: present

- name: install containerd.io
  apt:
    name: containerd.io
    state: present

- name: change cgroup
  shell: |
    cat <<EOF | sudo tee /etc/docker/daemon.json
    {
      "exec-opts": ["native.cgroupdriver=systemd"],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "storage-driver": "overlay2"
    }
    EOF

- name: restart dockerservice
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Configureing the systemd cgroup driver
  block:
  - name: Ensure containerd is installed.
    package:
      name: containerd.io
      state: present

  - name: Ensure containerd is started and enabled at boot.
    service:
      name: containerd
      state: started
      enabled: true

  - name: Ensure containerd config directory exists.
    file:
      path: /etc/containerd
      state: directory
    register: containerd_dir

  - name: Get defaults from containerd.
    command: containerd config default
    changed_when: false
    register: containerd_config_default

  - name: Prepare containerd/config.toml from default config
    copy:
      dest: /tmp/containerd_config.toml
      content: "{{ containerd_config_default.stdout }}"
    changed_when: false

  - name: Set Cgroup driver to systemd
    lineinfile:
      insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
      line: '            SystemdCgroup = true'
      state: present
      path: /tmp/containerd_config.toml
    changed_when: false

  - name: Make sure  SystemdCgroup = false is not set
    ansible.builtin.lineinfile:
      path: /tmp/containerd_config.toml
      state: absent
      line: '            SystemdCgroup = false'
    changed_when: false

  - name: Copy config.toml to /etc/containerd
    copy:
      remote_src: true
      src: /tmp/containerd_config.toml
      dest: /etc/containerd/config.toml

  - name: Cleanup temporary file
    file:
      path: /tmp/containerd_config.toml
      state: absent
    changed_when: false

  - name: Ensure containerd is restarted immediately if necessary.
    meta: flush_handlers

- name: restart containerd
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: containerd
