services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=pass
      - AWS_ACCESS_KEY_ID=004d9a838e5854c000000000d
      - AWS_SECRET_ACCESS_KEY=K004BhlsOnlnBrYJio9yLPSBrmC6FCw
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse-s3.xml:/etc/clickhouse-server/config.d/clickhouse-s3.xml

  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.124.0
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml
      - ./sample.log:/tmp/sample.log
    ports:
      - "4317:4317"   # gRPC
      - "4318:4318"   # HTTP
    depends_on:
      clickhouse:
        condition: service_started

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #    - '3000:3000'
  #   environment:
  #     - GF_PLUGINS_PREINSTALL=grafana-clickhouse-datasource
  #   volumes:
  #     - ./grafana:/etc/grafana/provisioning
